# Site settings
title: Ushahidi Platform v3.0 Docs
email: robbie@ushahidi.com
description: "Guides and documentation for Ushahidi Platform v3.0"
baseurl: ""
url: "http://docs.ushahidi.org/"

# Build settings
markdown: redcarpet
highlighter: pygments

redcarpet:
  extensions: ["tables", "fenced_code_blocks"]
