# Site settings
title: Ushahidi Guide
email: bostoncello@gmail.com
description: "Ushahidi docs for practices and tools around v3 Ushahidi platform"
baseurl: "/docs.ushahidi.com/"
url: "http://ushahidi.github.io/"
twitter_username: jcrowley
github_username:  jcrowley

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5


# prose.io settings
prose:
    rooturl: _posts
    siteurl: http://jcrowley.net/guide
    metadata:
        _posts:
          - name: "layout"
            field:
              element: "hidden"
              value: "post"
          - name: "category"
            field:
              element: "multiselect"
              label: "Category"
              help: "Categorize this post"
              options: 
                  - name: 'Guide'
                    value: 'guide'
                  - name: 'Toolkit'
                    value: 'toolkit'  
                  - name: 'Quickstart'
                    value: 'quickstart'
                  - name: 'Resource'
                    value: 'resource'         
              placeholder: 'guide'                   