# Site settings
title: Ushahidi v3.0 Docs
email: robbie@ushahidi.com
description: "Guides and documentation for Ushahidi v3.0"
baseurl: ""
url: "http://docs.ushahidi.org/"

# Build settings
markdown: redcarpet
highlighter: pygments

redcarpet:
  extensions: ["tables", "fenced_code_blocks", "with_toc_data", "autolink"]
