site_name: Ushahidi Platform
site_description: Guides and documentation for Ushahidi
site_author: Ushahidi Inc and Contributors
docs_dir: docs/
theme: readthedocs
markdown_extensions:
    - toc:
        permalink: true
pages:
- 'Home': 'index.md'
- 'get-involved.md'
- Install:
    - 'install/overview.md'
    - 'install/installing-on-heroku.md'
    - 'install/installing-on-linux.md'
    - 'install/installing-with-vagrant.md'
- 'Developer Guide':
    - 'developer-guide/overview.md'
    - 'developer-guide/adding-code.md'
